#!/bin/python
# psql -d postfs -c "insert into \"$POSTFSPWD\" (name, is_folder) values ('$1', true)"
# psql -Upostgres -d postfs -c "create table \"$POSTFSPWD\$1\"(name text, is_folder boolean)"

import os
import dbcon
import sys

dbcon.runq(f'insert into \"{dbcon.getpwd()}\" (name, is_folder) values (\'{sys.argv[1]}\', true)')
dbcon.runq(f'create table \"{dbcon.getpwd()}\{sys.argv[1]}\"(name text, is_folder boolean)')
