#!/bin/python
# createdb postfs
# export POSTFSPWD="$PWD"
# echo "$PWD" > POSTFSPWD
# psql -Upostgres -d postfs -c "create table \"$POSTFSPWD\"(name text, is_folder boolean)"
# export PATH="$PWD:$PATH"

import psycopg2
import os

try:
    connection = psycopg2.connect(user = os.popen('whoami').read(),
                                  password = "",
                                  host = "127.0.0.1",
                                  port = "5432",
                                  database = "postgres_db")

    cursor = connection.cursor()
    # Print PostgreSQL Connection properties
    print ( connection.get_dsn_parameters(),"\n")

    # Print PostgreSQL version
    cursor.execute("SELECT version();")
    record = cursor.fetchone()
    print("You are connected to - ", record,"\n")

except (Exception, psycopg2.Error) as error :
    print ("Error while connecting to PostgreSQL", error)
finally:
    #closing database connection.
        if(connection):
            cursor.close()
            connection.close()
            print("PostgreSQL connection is closed")
