#!/bin/python
# createdb postfs
# export POSTFSPWD="$PWD"
# echo "$PWD" > POSTFSPWD
# psql -Upostgres -d postfs -c "create table \"$POSTFSPWD\"(name text, is_folder boolean)"
# export PATH="$PWD:$PATH"

import os
import dbcon

os.system('createdb postfs')
open('./POSTFSPWD', 'w').write(os.getcwd())
dbres = dbcon.runq(f'create table "{dbcon.getpwd()}"(name text, is_folder boolean);', user='postgres')
dbcon.grant(os.popen('whoami').read())
print(dbres)
